AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppRunnerServiceArn:
    Type: String
    Description: ARN of the App Runner service
Resources:
  CIDeployerUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: CIDeployer

  AppRunnerDeploymentPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for CircleCI Deployer
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - 'apprunner:PauseService'
              - 'apprunner:UntagResource'
              - 'apprunner:DescribeService'
              - 'apprunner:ResumeService'
              - 'apprunner:ListTagsForResource'
              - 'apprunner:DescribeOperation'
              - 'apprunner:ListOperations'
              - 'apprunner:StartDeployment'
              - 'apprunner:TagResource'
            Resource: !Ref AppRunnerServiceArn
          - Sid: VisualEditor1
            Effect: Allow
            Action: 'apprunner:ListServices'
            Resource: '*'

  CIDeployerUserPolicyAttachment:
    Type: 'AWS::IAM::PolicyAttachment'
    Properties:
      PolicyArn: !Ref AppRunnerDeploymentPolicy
      Users:
        - !Ref CIDeployerUser
