Description: Resources necessary for running the app

Parameters:
  GitHubConnectionArn:
    Type: String
    Description: GitHubConnection ARN

  GitHubRepository:
    Type: String
    Description: GitHub repository URL

  AppRunnerServiceName:
    Type: String
    Description: Name of the app runner service

Resources:
  PygAppRunner:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref AppRunnerServiceName
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref GitHubConnectionArn
        AutoDeploymentsEnabled: false
        CodeRepository:
          RepositoryUrl: !Ref GitHubRepository
          SourceCodeVersion:
            Type: BRANCH
            Value: master
          CodeConfiguration:
            ConfigurationSource: REPOSITORY
      InstanceConfiguration:
        Cpu: 0.25 vCPU
        Memory: 0.5 GB
        InstanceRoleArn: !GetAtt Role.Arn

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: urls-new
      AttributeDefinitions:
        - AttributeName: shortcode
          AttributeType: S
      KeySchema:
        - AttributeName: shortcode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      # TimeToLiveSpecification:
      #   AttributeName: ttl
      #   Enabled: true
  
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ 'tasks.apprunner.amazonaws.com' ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: ddb-access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:ConditionCheckItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt Table.Arn

Outputs:
  RoleName:
    Description: Name of the role created for accessing DynamoDB
    Value: !Ref Role
  TableName:
    Description: DynamoDB table name
    Value: !Ref Table
